In [1]:
# Проверка версии, либо pip show pandas в терминале

import pandas as pd
import numpy as np

print(pd.__version__)
print(pd.show_versions(as_json=True))

2.2.2
{
  "system": {
    "commit": "d9cdd2ee5a58015ef6f4d15c7226110c9aab8140",
    "python": "3.12.5.final.0",
    "python-bits": 64,
    "OS": "Windows",
    "OS-release": "10",
    "Version": "10.0.19045",
    "machine": "AMD64",
    "processor": "AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD",
    "byteorder": "little",
    "LC_ALL": null,
    "LANG": null,
    "LOCALE": {
      "language-code": "Russian_Russia",
      "encoding": "1251"
    }
  },
  "dependencies": {
    "pandas": "2.2.2",
    "numpy": "2.1.0",
    "pytz": "2024.1",
    "dateutil": "2.9.0.post0",
    "setuptools": "74.0.0",
    "pip": "26.1.2",
    "Cython": null,
    "pytest": null,
    "hypothesis": null,
    "sphinx": null,
    "blosc": null,
    "feather": null,
    "xlsxwriter": null,
    "lxml.etree": "6.1.1",
    "html5lib": "1.1",
    "pymysql": null,
    "psycopg2": null,
    "jinja2": "3.1.6",
    "IPython": "9.2.0",
    "pandas_datareader": null,
    "adbc-driver-postgresql": null,
    "adbc-driver-sqlite": null,
    "bs4": "4.15.0",
    "bottleneck": null,
    "dataframe-api-compat": null,
    "fastparquet": null,
    "fsspec": null,
    "gcsfs": null,
    "matplotlib": null,
    "numba": null,
    "numexpr": null,
    "odfpy": null,
    "openpyxl": "3.1.5",
    "pandas_gbq": null,
    "pyarrow": null,
    "pyreadstat": null,
    "python-calamine": null,
    "pyxlsb": null,
    "s3fs": null,
    "scipy": null,
    "sqlalchemy": "2.0.51",
    "tables": null,
    "tabulate": null,
    "xarray": null,
    "xlrd": "2.0.2",
    "zstandard": null,
    "tzdata": "2024.1",
    "qtpy": null,
    "pyqt5": null
  }
}None

In [7]:
# Преобазование списка, массива numpy и словаря в объект Series

import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

mylist_p=pd.Series(mylist)
myarr_p=pd.Series(myarr)
mydict_p=pd.Series(mydict)

type(mylist_p), type(myarr_p), type(mydict_p)

(pandas.core.series.Series,
 pandas.core.series.Series,
 pandas.core.series.Series)

In [10]:
# Создание датафрейма из разных структур данных

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df=pd.DataFrame({'col1': ser1, 'col2': ser2}) # или df=pd.concat([ser1, ser2], axis=1)
df.head()

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [12]:
# Изменение имени серии

ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'alphabets'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [17]:
# Фильтрация значений в Series с помощью маски

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Метод isin() проверяет, есть ли каждый элемент ser1 внутри ser2. Он возвращает булеву маску 
# ~ отрицает True условие
res=ser1[~ser1.isin(ser2)]
res

0    1
1    2
2    3
dtype: int64

In [9]:
# Нахождение симметрической разницы
# Тоже самое, что ниже, но короче 
# pd.Series(np.setxor1d(ser1, ser2))

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# np.union1d(ser1, ser2) - Объединение
# Она берет два массива, объединяет их и убирает дубликаты, возвращая отсортированный массив уникальных значений.
ser_u = pd.Series(np.union1d(ser1, ser2))  # union

# np.intersect1d(ser1, ser2) — Пересечение
# Возвращает только те элементы, которые есть в обоих массивах одновременно (тоже отсортированные и уникальные).
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
print(ser_i)

# Отрицание маски
ser_u[~ser_u.isin(ser_i)]

0    4
1    5
dtype: int64

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [29]:
# Базовая статистика через метод numpy и через метод pandas
# Один проход по массиву, очень быстро

state = np.random.default_rng(100)
ser = pd.Series(state.normal(10, 5, size=25))

res1=np.percentile(ser, q=[0, 25, 50, 75, 100])
res2=ser.quantile([0, 0.25, 0.50, 0.75, 1.0])

res1,res2

(array([ 0.34449292,  6.55441142, 11.44877901, 13.72531301, 21.21486198]),
 0.00     0.344493
 0.25     6.554411
 0.50    11.448779
 0.75    13.725313
 1.00    21.214862
 dtype: float64)

In [18]:
# value_counts() подсчет количества уникальных элементов в серии
# Аналог collecions.Counter, но возвращает не словарь, а Series

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

b    7
a    6
e    4
g    4
f    3
c    3
d    2
h    1
Name: count, dtype: int64

In [ ]:
# Создаем генератор с фиксированным зерном
rng = np.random.default_rng(100)

# Используем его метод integers вместо randint
ser = pd.Series(rng.integers(1, 5, size=12))

# Находим два самых частых значения
top2 = ser.value_counts().head(2).index
print(top2)

# Оставляем их, остальное заменяем на "Другое"
result = ser.where(ser.isin(top2), 'Другое')

# Либо так:
# result = pd.Series(np.where(ser.isin(top2), ser, 'Другое'))

# Либо так:
# result = ser.mask(~ser.isin(top2), 'Другое')

print(result)

Index([4, 1], dtype='int64')
0          4
1          4
2          1
3     Другое
4          1
5     Другое
6     Другое
7          1
8     Другое
9          4
10         4
11    Другое
dtype: object

In [38]:
# Децили (Deciles)
# Определение: Делят данные на 10 равных частей по количеству наблюдений. Каждый дециль содержит ~10% данных.

# Квартили (Quartiles)
# Определение: Делят данные на 4 равные части. Каждый квартиль содержит ~25% данных.

# Процентили (Percentiles)
# Определение: Делят данные на 100 равных частей. Каждый процентиль содержит ~1% данных.

In [37]:
# Децили — это квантили, которые делят данные на 10 равных частей по количеству наблюдений. 
# То есть в каждом дециле будет примерно одинаковое число элементов (в нашем случае: 20 / 10 = по 2 элемента в каждом дециле).

ser = pd.Series(np.random.random(20))

# Разбиваем на 10 децилей с именованными метками
# q=10 — на сколько частей разбить (10 децилей)
# Делит на группы с одинаковым количеством элементов
result = pd.qcut(ser, q=10, labels=[f'D{i}' for i in range(1, 11)])

# Делит на группы с одинаковой шириной интервала
result2= pd.cut(ser, bins=10).value_counts()

print(result)
print(result2)

0      D1
1      D9
2      D5
3      D4
4      D6
5      D7
6      D2
7      D2
8      D7
9      D9
10     D4
11    D10
12     D8
13     D1
14    D10
15     D5
16     D3
17     D3
18     D6
19     D8
dtype: category
Categories (10, object): ['D1' < 'D2' < 'D3' < 'D4' ... 'D7' < 'D8' < 'D9' < 'D10']
(0.315, 0.413]    5
(0.02, 0.119]     4
(0.51, 0.608]     4
(0.902, 1.0]      2
(0.119, 0.217]    1
(0.217, 0.315]    1
(0.413, 0.51]     1
(0.608, 0.706]    1
(0.706, 0.804]    1
(0.804, 0.902]    0
Name: count, dtype: int64

In [5]:
# Преобразование Series в датафрейм заданного размера

ser = pd.Series(np.random.randint(1, 10, 35))
df=pd.DataFrame(ser.values.reshape(7,5))
df

   0  1  2  3  4
0  2  3  3  1  8
1  7  1  2  4  7
2  5  7  3  5  7
3  4  6  8  4  8
4  8  2  1  2  4
5  2  6  8  3  3
6  4  2  2  8  5

In [45]:
# Поиск индексов в Series по какому-то условию

ser = pd.Series(np.random.randint(1, 10, 7))
res=np.argwhere(ser%3==0)
res

array([[1],
       [4],
       [6]])

In [61]:
# Извлечение элементов Series по индексам из списка

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [84]:
# Вертикальное и горизонтальное объединение Series в датафрейм

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))


df=pd.concat([ser1,ser2], axis=1, keys=['numbers', 'letters'])
df2=pd.concat([ser1,ser2], axis=0)

df,df2

(   numbers letters
 0        0       a
 1        1       b
 2        2       c
 3        3       d
 4        4       e,
 0    0
 1    1
 2    2
 3    3
 4    4
 0    a
 1    b
 2    c
 3    d
 4    e
 dtype: object)

In [100]:
# Поиск индекса элемента ser2 в ser1 с сохранением порядка как в ser2
# get_loc ищет индекс по значению в pd.index(ser1)

ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

res=[pd.Index(ser1).get_loc(el) for el in ser2]
res

[5, 4, 0, 8]

In [101]:
# MSE (Mean Squared Error) — это метрика, которая показывает, насколько сильно предсказания отличаются от реальных значений.
# Среднее значение квадратов разностей между истиной и предсказанием 
# Чем меньше MSE, тем точнее предсказания.


truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

# Способ 1: вручную (по формуле)
mse = ((truth - pred) ** 2).mean()
print(f"MSE: {mse:.4f}")

# Способ 2: через sklearn (профессиональный)
from sklearn.metrics import mean_squared_error
mse_sklearn = mean_squared_error(truth, pred)
print(f"MSE (sklearn): {mse_sklearn:.4f}")

MSE: 0.2641
MSE (sklearn): 0.2641

In [111]:
# Каждая буква элемента Series заглавная

er = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.str.capitalize() # или ser.str.title()

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [118]:
# Подсчет количества элементов каждом слове

ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [123]:
# Вычисление разницы между соседними элементами
# diff() автоматически подставляет предыдущий элемент

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
stage1=ser.diff()
res=stage1.diff() # или ser.diff().diff()
print(stage1)
print(res)

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64
0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64

In [128]:
# Преобразование любого формата даты в datetime64
# format='mixed' для каждого элемента свой шаблон
# dayfirst=True Интерпретирует 02-03-2011 как 2 марта (европейский стиль)

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
res=pd.to_datetime(ser, format='mixed', dayfirst=True)
res

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [138]:
# После преобразования в datetime, можно использовать методы dt, чтобы выташить и отформатировать дату как захочется

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

datetimes=pd.to_datetime(ser, format='mixed', dayfirst=True)

days=datetimes.dt.day.to_list()
weeks=datetimes.dt.isocalendar().week.to_list()
day_nums=datetimes.dt.day_of_year.to_list()
days_of_week=datetimes.dt.day_name().to_list()

print(days)
print(weeks)
print(day_nums)
print(days_of_week)

[1, 2, 3, 4, 5, 6]
[53, 5, 9, 14, 19, 23]
[1, 33, 63, 94, 125, 157]
['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']

In [150]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
datetimes = pd.to_datetime(ser, format='%b %Y')  # убираем предупреждение

# Добавляем к datetime64 какой-то период через pd.to_timedelta
result = datetimes + pd.to_timedelta(3, unit='D')

print(result)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [178]:
# Регулярное выражение [aeiouAEIOU] означает "любая гласная буква (строчная или заглавная)". 
# Метод count() считает количество совпадений в каждом слове

ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

res = ser[ser.str.count('[aeiouAEIOU]') >= 2]
res

0     Apple
1    Orange
4     Money
dtype: object